name: GetPing
version: 1.0.0
author: DerCommander610
main: DerCommander610\Ping\Main
api: [5.1.2]
commands:
  getping:
    description: "Get a Players ping or your ping!"
    permission: ping.command.use

permissions:
   ping.command.use:
    default: true
